name: Publish Minecraft Mod

on:
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish mod using mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: yDPoAfcm
          modrinth-featured: false
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1108180
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ github.event.release.tag_name }}
          github-generate-changelog: false
          github-draft: false
          github-prerelease: false
          github-commitish: ${{ github.event.release.target_commitish }}
          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            build/libs/animal_trades-${{ github.event.release.tag_name }}-${{ github.event.release.name.split(" ")[-1] }}.jar

          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.name.split(" ")[-1] }}
          version-type: release

          changelog: ${{ github.event.release.body }}

          loaders: |
            forge

          game-versions: |
            ${{ github.event.release.tag_name }}

          dependencies: |
            required-dependency
            optional-dependency@0.1.0(optional)
            recommended-dependency@0.2.0(recommended)
            embedded-dependency@0.3.0(embedded)
            conflicting-dependency(conflicting)
            incompatible-dependency(incompatible)

          java: |
            ${{ github.ref == 'refs/heads/1.21.1' && '21' ||
               github.ref == 'refs/heads/1.20.6' && '21' ||
               github.ref == 'refs/heads/1.19.4' && '17' ||
               github.ref == 'refs/heads/1.18.2' && '17' ||
               github.ref == 'refs/heads/1.17.1' && '16' ||
               github.ref == 'refs/heads/1.16.5' && '16' ||
               '8' }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
